name: YTS Movie Scraper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 3 * * *'  # This will run every day at 6 AM UTC, which is 3 AM EAT
  workflow_dispatch:

permissions: write-all
  
jobs:
  scrape_movies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade pip && pip install -r requirements.txt # Include openpyxl here
      - name: Run Python script
        run: python yts-scraper.py  # Replace with the name of your Python script
        
      - name: Display Excel File and Post Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -c "
          import pandas as pd
          import datetime
          df = pd.read_excel('output.xlsx')
          now = datetime.datetime.now()
          date_time_day = now.strftime('%Y-%m-%d')
          report_file = 'report_' + date_time_day + '.md'
          with open(report_file, 'w') as f:
              f.write(df.to_markdown())"
          cml comment create report_file