name: YTS Movie Scraper

on:
  schedule:
    - cron: '0 3 * * *'  # This will run every day at 6 AM UTC, which is 3 AM EAT

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
            with:
              lfs: true
          - name: Setup CML
            uses: iterative/setup-cml@v2
          - name: Install Python dependencies
            run: |
              pip install --upgrade pip
              pip install -r requirements.txt
          - name: Run code
            run: python code.ipynb  
          - name: Display Excel File
            run: |
              python -c "
              import pandas as pd
              df = pd.read_excel('output.xlsx')
              print(df.to_markdown())" >> report.md
          - name: Post report
            run: cml comment create report.md
