name: YTS Movie Scraper

on:
 schedule:
    - cron: '0 3 * * *' # This will run every day at 3 AM UTC, which is 6 AM Kenyan time
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]
 workflow_dispatch:

permissions: write-all

jobs:
 scrape_and_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run YTS Scraper
        run: python yts_scraper.py

      - name: Upload Excel File
        uses: actions/upload-artifact@v2
        with:
          name: output-excel
          path: output.xlsx

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: report-markdown
          path: report.md
