name: YTS Movie Scraper

on:
  schedule:
    - cron: '0 3 * * *'  # This will run every day at 6 AM UTC, which is 3 AM EAT
  workflow_dispatch:
  
jobs:
  scrape_movies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 pandas openpyxl  # Include openpyxl here

      - name: Run Python script
        run: python yts-scraper.py  # Replace with the name of your Python script

      - name: Display Excel File
        run: |
          python -c "
          import pandas as pd
          df = pd.read_excel('output.xlsx')
          print(df.to_markdown())" >> report.md
